INSERT INTO ccApp.produkty (id_produkty, nazwa, jednostka) VALUES
('1', 'Jajka', 'szt'),
('2', 'Kurczak', 'szt'),
('3', 'Pomidor', 'szt'),
('4', 'Maka', 'g'),
('5', 'Makaron', 'g'),
('6', 'Kostka rosolowa', 'szt'),
('7', 'Cebula', 'szt'),
('8', 'Papryka', 'szt'),
('9', 'Przecier pomidorowy', 'lyzka/i'),
('10', 'Zabek czosnku', 'szt'),
('11', 'Mozarella', 'g'),
('12', 'Olej', 'lyzka/i'),
('13', 'Woda', 'szkl'),
('14', 'Kurczak', 'g'),
('15', 'Przyprawa do gyrosa', 'lyzeczka/i'),
('16', 'Kapusta pekinska', 'g'),
('17', 'Czerwona cebula', 'szt'),
('18', 'Kukurydza z puszki', 'opak'),
('19', 'Ogorki konserwowe', 'szt'),
('20', 'Majonez', 'g'),
('21', 'Ketchup', 'g'),
('22', 'Przyprawa do kurczaka', 'lyzeczka/i'),
('23', 'Woda', 'ml'),
('24', 'Smietana 18%', 'ml'),
('25', 'Maka', 'lyzka/i'),
('26', 'Olej', 'ml'),
('27', 'Natka pietruszki', 'szt'),
('28', 'Ser', 'g'),
('29', 'Przyprawa uniwersalna', 'lyzeczka/i'),
('30', 'Szpinak mrozony', 'opak'),
('31', 'Warzywa na patelnie', 'g'),
('32', 'Ryz', 'g'),
('33', 'Maslo', 'g'),
('34', 'Smietana', 'lyzka/i'),
('35', 'Oliwa', 'lyzka/i');

INSERT INTO ccApp.dzien (numer_dnia) VALUES 
(1), (2), (3), (4), (5), (6), (7), (8), (9), (10),
(11), (12), (13), (14), (15), (16), (17), (18), (19), (20),
(21), (22), (23), (24), (25), (26), (27), (28), (29), (30), (31);